### ISSUE TITLE
Can you make headers having default values optional?

### ISSUE THREAD

**Issue by LandonGrey9** [brianxor/tls-api#2]
Hello,
Can you make headers having default values optional? As an example, in the readme, the default value for x-tls-client-timeout is mentioned as 30 then it should take value 30 when we do not pass it explicitly? So that it reduces the hassle to pass those headers every time?
Also, can we let the library (tls-client) decide the values of x-tls-header-order and x-tls-pseudo-header-order headers if we do not pass them?

**Comment by brianxor** [comment]
Hi,

I can make it pass default values for some of the options, but you should always add the header order yourself as it matters for tls fingerprinting

**Comment by brianxor** [comment]
@LandonGrey9 However, i added default values for the majority, please check [v1.2.4](https://github.com/brianxor/tls-api/releases/tag/v1.2.4).

Thank you.
